name: Retail - CI/CD

on:
  push:
    tags: ["**"]
    branches: ["master", "develop"]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      # Run the GitHub Action for the packager project
      - name: Package and release
        uses: BigWigsMods/packager@master
